/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharePublic_urlRouteImport } from './routes/share/$public_url'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedUUserRouteImport } from './routes/_authenticated/u/$user'
import { Route as AuthenticatedViewTuneTuneIdRouteImport } from './routes/_authenticated/view/tune/$tuneId'
import { Route as AuthenticatedViewCarCarIdRouteImport } from './routes/_authenticated/view/car/$carId'
import { Route as AuthenticatedTuneEditTuneIdRouteImport } from './routes/_authenticated/tune/edit/$tuneId'
import { Route as AuthenticatedTuneCarCarIdRouteImport } from './routes/_authenticated/tune/car/$carId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharePublic_urlRoute = SharePublic_urlRouteImport.update({
  id: '/share/$public_url',
  path: '/share/$public_url',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUserRoute = AuthenticatedUUserRouteImport.update({
  id: '/u/$user',
  path: '/u/$user',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedViewTuneTuneIdRoute =
  AuthenticatedViewTuneTuneIdRouteImport.update({
    id: '/view/tune/$tuneId',
    path: '/view/tune/$tuneId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedViewCarCarIdRoute =
  AuthenticatedViewCarCarIdRouteImport.update({
    id: '/view/car/$carId',
    path: '/view/car/$carId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTuneEditTuneIdRoute =
  AuthenticatedTuneEditTuneIdRouteImport.update({
    id: '/tune/edit/$tuneId',
    path: '/tune/edit/$tuneId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTuneCarCarIdRoute =
  AuthenticatedTuneCarCarIdRouteImport.update({
    id: '/tune/car/$carId',
    path: '/tune/car/$carId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/search': typeof AuthenticatedSearchRoute
  '/share/$public_url': typeof SharePublic_urlRoute
  '/u/$user': typeof AuthenticatedUUserRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tune/car/$carId': typeof AuthenticatedTuneCarCarIdRoute
  '/tune/edit/$tuneId': typeof AuthenticatedTuneEditTuneIdRoute
  '/view/car/$carId': typeof AuthenticatedViewCarCarIdRoute
  '/view/tune/$tuneId': typeof AuthenticatedViewTuneTuneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/search': typeof AuthenticatedSearchRoute
  '/share/$public_url': typeof SharePublic_urlRoute
  '/u/$user': typeof AuthenticatedUUserRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tune/car/$carId': typeof AuthenticatedTuneCarCarIdRoute
  '/tune/edit/$tuneId': typeof AuthenticatedTuneEditTuneIdRoute
  '/view/car/$carId': typeof AuthenticatedViewCarCarIdRoute
  '/view/tune/$tuneId': typeof AuthenticatedViewTuneTuneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/share/$public_url': typeof SharePublic_urlRoute
  '/_authenticated/u/$user': typeof AuthenticatedUUserRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tune/car/$carId': typeof AuthenticatedTuneCarCarIdRoute
  '/_authenticated/tune/edit/$tuneId': typeof AuthenticatedTuneEditTuneIdRoute
  '/_authenticated/view/car/$carId': typeof AuthenticatedViewCarCarIdRoute
  '/_authenticated/view/tune/$tuneId': typeof AuthenticatedViewTuneTuneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/verify-email'
    | '/browse'
    | '/search'
    | '/share/$public_url'
    | '/u/$user'
    | '/dashboard'
    | '/settings'
    | '/tune/car/$carId'
    | '/tune/edit/$tuneId'
    | '/view/car/$carId'
    | '/view/tune/$tuneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/verify-email'
    | '/browse'
    | '/search'
    | '/share/$public_url'
    | '/u/$user'
    | '/dashboard'
    | '/settings'
    | '/tune/car/$carId'
    | '/tune/edit/$tuneId'
    | '/view/car/$carId'
    | '/view/tune/$tuneId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/verify-email'
    | '/_authenticated/browse'
    | '/_authenticated/search'
    | '/share/$public_url'
    | '/_authenticated/u/$user'
    | '/_authenticated/dashboard/'
    | '/_authenticated/settings/'
    | '/_authenticated/tune/car/$carId'
    | '/_authenticated/tune/edit/$tuneId'
    | '/_authenticated/view/car/$carId'
    | '/_authenticated/view/tune/$tuneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  SharePublic_urlRoute: typeof SharePublic_urlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$public_url': {
      id: '/share/$public_url'
      path: '/share/$public_url'
      fullPath: '/share/$public_url'
      preLoaderRoute: typeof SharePublic_urlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$user': {
      id: '/_authenticated/u/$user'
      path: '/u/$user'
      fullPath: '/u/$user'
      preLoaderRoute: typeof AuthenticatedUUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/view/tune/$tuneId': {
      id: '/_authenticated/view/tune/$tuneId'
      path: '/view/tune/$tuneId'
      fullPath: '/view/tune/$tuneId'
      preLoaderRoute: typeof AuthenticatedViewTuneTuneIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/view/car/$carId': {
      id: '/_authenticated/view/car/$carId'
      path: '/view/car/$carId'
      fullPath: '/view/car/$carId'
      preLoaderRoute: typeof AuthenticatedViewCarCarIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tune/edit/$tuneId': {
      id: '/_authenticated/tune/edit/$tuneId'
      path: '/tune/edit/$tuneId'
      fullPath: '/tune/edit/$tuneId'
      preLoaderRoute: typeof AuthenticatedTuneEditTuneIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tune/car/$carId': {
      id: '/_authenticated/tune/car/$carId'
      path: '/tune/car/$carId'
      fullPath: '/tune/car/$carId'
      preLoaderRoute: typeof AuthenticatedTuneCarCarIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedUUserRoute: typeof AuthenticatedUUserRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTuneCarCarIdRoute: typeof AuthenticatedTuneCarCarIdRoute
  AuthenticatedTuneEditTuneIdRoute: typeof AuthenticatedTuneEditTuneIdRoute
  AuthenticatedViewCarCarIdRoute: typeof AuthenticatedViewCarCarIdRoute
  AuthenticatedViewTuneTuneIdRoute: typeof AuthenticatedViewTuneTuneIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedUUserRoute: AuthenticatedUUserRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTuneCarCarIdRoute: AuthenticatedTuneCarCarIdRoute,
  AuthenticatedTuneEditTuneIdRoute: AuthenticatedTuneEditTuneIdRoute,
  AuthenticatedViewCarCarIdRoute: AuthenticatedViewCarCarIdRoute,
  AuthenticatedViewTuneTuneIdRoute: AuthenticatedViewTuneTuneIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  SharePublic_urlRoute: SharePublic_urlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
