/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedProfileTunesRouteImport } from './routes/_authenticated/profile/tunes'
import { Route as AuthenticatedViewTuneTuneIdRouteImport } from './routes/_authenticated/view/tune/$tuneId'
import { Route as AuthenticatedViewCarCarIdRouteImport } from './routes/_authenticated/view/car/$carId'
import { Route as AuthenticatedTuneCarCarIdRouteImport } from './routes/_authenticated/tune/car/$carId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileTunesRoute =
  AuthenticatedProfileTunesRouteImport.update({
    id: '/profile/tunes',
    path: '/profile/tunes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedViewTuneTuneIdRoute =
  AuthenticatedViewTuneTuneIdRouteImport.update({
    id: '/view/tune/$tuneId',
    path: '/view/tune/$tuneId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedViewCarCarIdRoute =
  AuthenticatedViewCarCarIdRouteImport.update({
    id: '/view/car/$carId',
    path: '/view/car/$carId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTuneCarCarIdRoute =
  AuthenticatedTuneCarCarIdRouteImport.update({
    id: '/tune/car/$carId',
    path: '/tune/car/$carId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/profile/tunes': typeof AuthenticatedProfileTunesRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/tune/car/$carId': typeof AuthenticatedTuneCarCarIdRoute
  '/view/car/$carId': typeof AuthenticatedViewCarCarIdRoute
  '/view/tune/$tuneId': typeof AuthenticatedViewTuneTuneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/profile/tunes': typeof AuthenticatedProfileTunesRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/tune/car/$carId': typeof AuthenticatedTuneCarCarIdRoute
  '/view/car/$carId': typeof AuthenticatedViewCarCarIdRoute
  '/view/tune/$tuneId': typeof AuthenticatedViewTuneTuneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/profile/tunes': typeof AuthenticatedProfileTunesRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/tune/car/$carId': typeof AuthenticatedTuneCarCarIdRoute
  '/_authenticated/view/car/$carId': typeof AuthenticatedViewCarCarIdRoute
  '/_authenticated/view/tune/$tuneId': typeof AuthenticatedViewTuneTuneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-up'
    | '/browse'
    | '/profile/tunes'
    | '/profile'
    | '/tune/car/$carId'
    | '/view/car/$carId'
    | '/view/tune/$tuneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/browse'
    | '/profile/tunes'
    | '/profile'
    | '/tune/car/$carId'
    | '/view/car/$carId'
    | '/view/tune/$tuneId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/sign-up'
    | '/_authenticated/browse'
    | '/_authenticated/profile/tunes'
    | '/_authenticated/profile/'
    | '/_authenticated/tune/car/$carId'
    | '/_authenticated/view/car/$carId'
    | '/_authenticated/view/tune/$tuneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/tunes': {
      id: '/_authenticated/profile/tunes'
      path: '/profile/tunes'
      fullPath: '/profile/tunes'
      preLoaderRoute: typeof AuthenticatedProfileTunesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/view/tune/$tuneId': {
      id: '/_authenticated/view/tune/$tuneId'
      path: '/view/tune/$tuneId'
      fullPath: '/view/tune/$tuneId'
      preLoaderRoute: typeof AuthenticatedViewTuneTuneIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/view/car/$carId': {
      id: '/_authenticated/view/car/$carId'
      path: '/view/car/$carId'
      fullPath: '/view/car/$carId'
      preLoaderRoute: typeof AuthenticatedViewCarCarIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tune/car/$carId': {
      id: '/_authenticated/tune/car/$carId'
      path: '/tune/car/$carId'
      fullPath: '/tune/car/$carId'
      preLoaderRoute: typeof AuthenticatedTuneCarCarIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedProfileTunesRoute: typeof AuthenticatedProfileTunesRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedTuneCarCarIdRoute: typeof AuthenticatedTuneCarCarIdRoute
  AuthenticatedViewCarCarIdRoute: typeof AuthenticatedViewCarCarIdRoute
  AuthenticatedViewTuneTuneIdRoute: typeof AuthenticatedViewTuneTuneIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedProfileTunesRoute: AuthenticatedProfileTunesRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedTuneCarCarIdRoute: AuthenticatedTuneCarCarIdRoute,
  AuthenticatedViewCarCarIdRoute: AuthenticatedViewCarCarIdRoute,
  AuthenticatedViewTuneTuneIdRoute: AuthenticatedViewTuneTuneIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
